export const survivorPerks = [
    {
        name: "Ace in the Hole",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/ace-in-the-hole.png",
        teachable: "Ace Visconti Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
    },
    {
        name: "Adrenaline",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/adrenaline.png",
        teachable: "Meg Thomas Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
    },
    {
        name: "After Care",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/after-care.png",
        teachable: "Jeff Johansen Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/15-jeff-johansen.png",
    },
    {
        name: "Alert",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/alert.png",
        teachable: "Feng Min Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/10-feng-min.png",
    },
    {
        name: "Any Means Necessary",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/any-means-necessary.png",
        teachable: "Yui Kimura Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/20-yui-kimura.png",
    },
    {
      name: "Appraisal",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/appraisal.png",
      teachable: "Élodie Rakoto Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/24-elodie-rakoto.png",
    },
    {
      name: "Autodidact",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/autodidact.png",
      teachable: "Adam Francis Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/14-adam-francis.png",
    },
    {
      name: "Guardian",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/babysitter.png",
      teachable: "Steve Harrington Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/19-steve-harrington.png",
    },
    {
      name: "Balanced Landing",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/balanced-landing.png",
      teachable: "Nea Karlsson Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
    },
    {
      name: "Situational Awareness",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/better-together.png",
      teachable: "Nancy Wheeler Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/18-nancy-wheeler.png",
    },
    {
      name: "Bite the Bullet",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/bite-the-bullet.png",
      teachable: "Leon S. Kennedy Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/27-leon-s-kennedy.png",
    },
    {
      name: "Blast Mine",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/blast-mine.png",
      teachable: "Jill Valentine Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/26-jill-valentine.png",
    },
    {
      name: "Blood Pact",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/blood-pact.png",
      teachable: "Cheryl Mason Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/22-cheryl-mason.png",
    },
    {
      name: "Boil Over",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/boil-over.png",
      teachable: "Kate Denson Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/13-kate-denson.png",
    },
    {
      name: "Bond",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/bond.png",
      teachable: "Dwight Fairfield Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
    },
    {
      name: "Boon: Circle of Healing",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/boon-circle-of-healing.png",
      teachable: "Mikaela Reid Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/28-mikaela-reid.png",
    },
    {
      name: "Boon: Dark Theory",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/boon-dark-theory.png",
      teachable: "Yoichi Asakawa Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/30-yoichi-asakawa.png",
    },
    {
      name: "Boon: Exponential",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/boon-exponential.png",
      teachable: "Jonah Vasquez Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/29-jonah-vasquez.png",
    },
    {
      name: "Boon: Shadow Step",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/boon-shadow-step.png",
      teachable: "Mikaela Reid Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/28-mikaela-reid.png",
    },
    {
      name: "Borrowed Time",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/borrowed-time.png",
      teachable: 'William "Bill" Overbeck Teachable Perk',
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/06-bill-overbeck.png",
    },
    {
      name: "Botany Knowledge",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/botany-knowledge.png",
      teachable: "Claudette Morel Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
    },
    {
      name: "Breakdown",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/breakdown.png",
      teachable: "Jeff Johansen Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/15-jeff-johansen.png",
    },
    {
      name: "Breakout",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/breakout.png",
      teachable: "Yui Kimura Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/20-yui-kimura.png",
    },
    {
      name: "Buckle Up",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/buckle-up.png",
      teachable: "Ashley J. Williams Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/17-ash-williams.png",
    },
    {
      name: "Built to Last",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/built-to-last.png",
      teachable: "Felix Richter Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/23-felix-richter.png",
    },
    {
      name: "Calm Spirit",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/calm-spirit.png",
      teachable: "Jake Park Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
    },
    {
      name: "Kinship",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/camaraderie.png",
      teachable: "Steve Harrington Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/19-steve-harrington.png",
    },
    {
      name: "Clairvoyance",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/clairvoyance.png",
      teachable: "Mikaela Reid Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/28-mikaela-reid.png",
    },
    {
      name: "Corrective Action",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/corrective-action.png",
      teachable: "Jonah Vasquez Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/29-jonah-vasquez.png",
    },
    {
      name: "Counterforce",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/counter-force.png",
      teachable: "Jill Valentine Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/26-jill-valentine.png",
    },
    {
      name: "Dance With Me",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/dance-with-me.png",
      teachable: "Kate Denson Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/13-kate-denson.png",
    },
    {
      name: "Dark Sense",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/dark-sense.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Dead Hard",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/dead-hard.png",
      teachable: "David King Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/07-david-king.png",
    },
    {
      name: "Deception",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/deception.png",
      teachable: "Élodie Rakoto Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/24-elodie-rakoto.png",
    },
    {
      name: "Decisive Strike",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/decisive-strike.png",
      teachable: "Laurie Strode Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
    },
    {
      name: "Déjà Vu",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/deja-vu.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Deliverance",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/deliverance.png",
      teachable: "Adam Francis Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/14-adam-francis.png",
    },
    {
      name: "Desperate Measures",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/desperate-measures.png",
      teachable: "Felix Richter Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/23-felix-richter.png",
    },
    {
      name: "Detectives Hunch",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/detectives-hunch.png",
      teachable: "Detective David Tapp Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/12-detective-david-tapp.png",
    },
    {
      name: "Distortion",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/distortion.png",
      teachable: "Jeff Johansen Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/15-jeff-johansen.png",
    },
    {
      name: "Diversion",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/diversion.png",
      teachable: "Adam Francis Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/14-adam-francis.png",
    },
    {
      name: "Empathic Connection",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/empathic-connection.png",
      teachable: "Yoichi Asakawa Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/30-yoichi-asakawa.png",
    },
    {
      name: "Empathy",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/empathy.png",
      teachable: "Claudette Morel Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
    },
    {
      name: "Fast Track",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/fast-track.png",
      teachable: "Yun-Jin Lee Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/25-yun-jin-lee.png",
    },
    {
      name: "Self-Aware",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/fixated.png",
      teachable: "Nancy Wheeler Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/18-nancy-wheeler.png",
    },
    {
      name: "Flashbang",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/flashbang.png",
      teachable: "Leon S. Kennedy Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/27-leon-s-kennedy.png",
    },
    {
      name: "Flip-Flop",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/flip-flop.png",
      teachable: "Ashley J. Williams Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/17-ash-williams.png",
    },
    {
      name: "For the People",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/for-the-people.png",
      teachable: "Zarina Kassir Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/21-zarina-kassir.png",
    },
    {
      name: "Head On",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/head-on.png",
      teachable: "Jane Romero Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/16-jane-romero.png",
    },
    {
      name: "Hope",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/hope.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Inner Healing",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/inner-strength.png",
      teachable: "Nancy Wheeler Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/18-nancy-wheeler.png",
    },
    {
      name: "Iron Will",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/iron-will.png",
      teachable: "Jake Park Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
    },
    {
      name: "Kindred",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/kindred.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Leader",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/leader.png",
      teachable: "Dwight Fairfield Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
    },
    {
      name: "Left Behind",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/left-behind.png",
      teachable: 'William "Bill" Overbeck Teachable Perk',
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/06-bill-overbeck.png",
    },
    {
      name: "Lightweight",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/lightweight.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Lithe",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/lithe.png",
      teachable: "Feng Min Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/10-feng-min.png",
    },
    {
      name: "Lucky Break",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/lucky-break.png",
      teachable: "Yui Kimura Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/20-yui-kimura.png",
    },
    {
      name: "Mettle of Man",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/mettle-of-man.png",
      teachable: "Ashley J. Williams Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/17-ash-williams.png",
    },
    {
      name: "No Mither",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/no-mither.png",
      teachable: "David King Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/07-david-king.png",
    },
    {
      name: "No One Left Behind",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/no-one-left-behind.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Object of Obsession",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/object-of-obsession.png",
      teachable: "Laurie Strode Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
    },
    {
      name: "Off the Record",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/off-the-record.png",
      teachable: "Zarina Kassir Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/21-zarina-kassir.png",
    },
    {
      name: "Open Handed",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/open-handed.png",
      teachable: "Ace Visconti Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
    },
    {
      name: "Overcome",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/overcome.png",
      teachable: "Jonah Vasquez Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/29-jonah-vasquez.png",
    },
    {
      name: "Parental Guidance",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/parental-guidance.png",
      teachable: "Yoichi Asakawa Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/30-yoichi-asakawa.png",
    },
    {
      name: "Pharmacy",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/pharmacy.png",
      teachable: "Quentin Smith Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/11-quentin-smith.png",
    },
    {
      name: "Plunderers Instinct",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/plunderers-instinct.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Poised",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/poised.png",
      teachable: "Jane Romero Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/16-jane-romero.png",
    },
    {
      name: "Power Struggle",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/power-struggle.png",
      teachable: "Élodie Rakoto Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/24-elodie-rakoto.png",
    },
    {
      name: "Premonition",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/premonition.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Prove Thyself",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/prove-thyself.png",
      teachable: "Dwight Fairfield Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
    },
    {
      name: "Quick and Quiet",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/quick-and-quiet.png",
      teachable: "Meg Thomas Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
    },
    {
      name: "Red Herring",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/red-herring.png",
      teachable: "Zarina Kassir Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/21-zarina-kassir.png",
    },
    {
      name: "Renewal",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/renewal.png",
      teachable: "Steve Harrington Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/19-steve-harrington.png",
    },
    {
      name: "Repressed Alliance",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/repressed-alliance.png",
      teachable: "Cheryl Mason Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/22-cheryl-mason.png",
    },
    {
      name: "Resilience",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/resilience.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Resurgence",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/resurgence.png",
      teachable: "Jill Valentine Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/26-jill-valentine.png",
    },
    {
      name: "Rookie Spirit",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/rookie-spirit.png",
      teachable: "Leon S. Kennedy Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/27-leon-s-kennedy.png",
    },
    {
      name: "Saboteur",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/saboteur.png",
      teachable: "Jake Park Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
    },
    {
      name: "Self-Care",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/self-care.png",
      teachable: "Claudette Morel Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
    },
    {
      name: "Self-Preservation",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/self-preservation.png",
      teachable: "Yun-Jin Lee Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/25-yun-jin-lee.png",
    },
    {
      name: "Slippery Meat",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/slippery-meat.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Small Game",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/small-game.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Smash Hit",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/smash-hit.png",
      teachable: "Yun-Jin Lee Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/25-yun-jin-lee.png",
    },
    {
      name: "Sole Survivor",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/sole-survivor.png",
      teachable: "Laurie Strode Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
    },
    {
      name: "Solidarity",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/solidarity.png",
      teachable: "Jane Romero Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/16-jane-romero.png",
    },
    {
      name: "Soul Guard",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/soul-guard.png",
      teachable: "Cheryl Mason Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/22-cheryl-mason.png",
    },
    {
      name: "Spine Chill",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/spine-chill.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Sprint Burst",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/sprint-burst.png",
      teachable: "Meg Thomas Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
    },
    {
      name: "Stake Out",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/stakeout.png",
      teachable: "Detective David Tapp Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/12-detective-david-tapp.png",
    },
    {
      name: "Streetwise",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/streetwise.png",
      teachable: "Nea Karlsson Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
    },
    {
      name: "Technician",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/technician.png",
      teachable: "Feng Min Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/10-feng-min.png",
    },
    {
      name: "Tenacity",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/tenacity.png",
      teachable: "Detective David Tapp Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/12-detective-david-tapp.png",
    },
    {
      name: "This Is Not Happening",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/this-is-not-happening.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "Unbreakable",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/unbreakable.png",
      teachable: 'William "Bill" Overbeck Teachable Perk',
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/06-bill-overbeck.png",
    },
    {
      name: "Up the Ante",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/up-the-ante.png",
      teachable: "Ace Visconti Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
    },
    {
      name: "Urban Evasion",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/urban-evasion.png",
      teachable: "Nea Karlsson Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
    },
    {
      name: "Vigil",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/vigil.png",
      teachable: "Quentin Smith Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/11-quentin-smith.png",
    },
    {
      name: "Visionary",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/visionary.png",
      teachable: "Felix Richter Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/23-felix-richter.png",
    },
    {
      name: "Wake Up",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/wake-up.png",
      teachable: "Quentin Smith Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/11-quentin-smith.png",
    },
    {
      name: "We'll Make It",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/well-make-it.png",
      teachable: "All Survivors",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/00-all-survivors.png",
    },
    {
      name: "We're Gonna Live Forever",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/were-gonna-live-forever.png",
      teachable: "David King Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/07-david-king.png",
    },
    {
      name: "Windows of Opportunity",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/windows-of-opportunity.png",
      teachable: "Kate Denson Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/13-kate-denson.png",
    },
    {
      name: "Inner Focus",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/inner-focus.png",
      teachable: "Haddie Kaur Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/31-haddie-kaur.png",
    },
    {
      name: "Residual Manifest",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/residual-manifest.png",
      teachable: "Haddie Kaur Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/31-haddie-kaur.png",
    },
    {
      name: "Overzealous",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/overzealous.png",
      teachable: "Haddie Kaur Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/31-haddie-kaur.png",
    },
    {
      name: "Better Than New",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/better-than-new.png",
      teachable: "Rebecca Chambers Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/33-rebecca-chambers.png",
    },
    {
      name: "Better Than New",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/better-than-new.png",
      teachable: "Rebecca Chambers Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/33-rebecca-chambers.png",
    },
    {
      name: "Hyperfocus",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/hyperfocus.png",
      teachable: "Rebecca Chambers Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/33-rebecca-chambers.png",
    },
    {
      name: "Reassurance",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/reassurance.png",
      teachable: "Rebecca Chambers Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/33-rebecca-chambers.png",
    },
    {
      name: "Low Profile",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/low-profile.png",
      teachable: "Ada Wong Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/32-ada-wong.png",
    },
    {
      name: "Wiretrap",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/wiretrap.png",
      teachable: "Ada Wong Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/32-ada-wong.png",
    },
    {
      name: "Reactive Healing",
      image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/reactive-healing.png",
      teachable: "Ada Wong Teachable Perk",
      survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/32-ada-wong.png",
    },
]